language: node_js

services:
  - docker

addons:
  ssh_known_hosts: dev-pece.dropit.in

# branches:
#   - dev

# Production Env Setup
before_install:
  - docker-compose run production

before_deploy:
  - openssl aes-256-cbc -K $encrypted_33c1172ef7ff_key -iv $encrypted_33c1172ef7ff_iv -in deploy-travisci.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# E2E Tests Setup
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 3 # give xvfb some time to start
  - nvm use default

script:
  - echo "Script Running..."
  - echo "[...]"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy-dev.sh
    on:
      branch: dev

after_success:
  - echo "Deployed Successfully! \o/"
