language: node_js

services:
  - docker

addons:
  ssh_known_hosts: dev-pece.dropit.in

before_deploy:
  - openssl aes-256-cbc -K $encrypted_33c1172ef7ff_key -iv $encrypted_33c1172ef7ff_iv -in deploy-travisci.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: sh deploy-update.sh
    # on:
    #   branch: fs/dev

after_success:
  - sh deploy.sh

# branches:
#   - dev

script:
  - docker-compose run production echo "Build ended"
