version: '2'

services:
  db_mysql:
    image: mysql:5.6
    container_name: pece-db-mysql
    environment:
      - MYSQL_USER=pece
      - MYSQL_DATABASE=pece
      - MYSQL_PASSWORD=ZwTuVZzQO90qwYzA
      - MYSQL_ROOT_PASSWORD=Sk82jxYqqpx02jxT
    # volumes:
    #   - ../databases/pece:/var/lib/mysql

  dev_pece:
    image: taller/pece
    build:
      context: ./
      dockerfile: ./docker/DockerfileDevelopment
    cap_add:
      - ALL
    hostname: "dev"
    working_dir: /pece/drupal
    environment:
      - DB_PORT=3306
      - DB_HOST=pece-db
      - DB_NAME=pece
      - DB_DRIVER=mysql
      - DB_USERNAME=pece
      - DB_PASSWORD=ZwTuVZzQO90qwYzA
    volumes:
      - $PWD:/pece/drupal
      - $HOME/.ssh:/pece/.ssh
      - $HOME/.gitconfig:/pece/.gitconfig
    container_name: pece-dev-apache
    links:
      - db_mysql:pece-db

  production:
    image: taller/pece
    cap_add:
      - ALL
    hostname: "prod"
    working_dir: /pece/drupal
    environment:
      - DB_PORT=3306
      - DB_HOST=pece-db
      - DB_NAME=pece
      - DB_DRIVER=mysql
      - DB_USERNAME=pece
      - DB_PASSWORD=ZwTuVZzQO90qwYzA
      - IS_PRODUCTION=true
    volumes:
      - $PWD:/pece/drupal
      - $HOME/.ssh:/pece/.ssh
      - $HOME/.gitconfig:/pece/.gitconfig
    container_name: pece-prod-apache
    links:
      - db_mysql:pece-db
    entrypoint: ./docker/docker-entrypoint-prod.sh
